### ISSUE TITLE
[1.7.10]: V1.11.7 - 1.12.2 Crash on Startup with the original archaicfix

### ISSUE THREAD

**Issue by PopcornHead51** [quentin452/Multithreadingandtweaks#100]
### Help isloating the issue

- [ ] Did you tried to disabling some mixins in the mod config to see what mixin made the issue?
- [ ] Did you find what mixin made the issue?

### Game log

[latest.log](https://github.com/quentin452/OptimizationsAndTweaks/files/13986719/latest.log)

### Description

Updating from 1.11.6 to any of the versions since as of writing causes this crash on startup. Seems to be biome-related.

**Comment by quentin452** [comment]
Use my fork of archaicfix, its caused by the usage of MixinMapGenStructure on archaicfix side on the original
