### ISSUE TITLE
1.7.10 crash with other mods

### ISSUE THREAD

**Issue by xdeadstokex** [quentin452/Multithreadingandtweaks#103]
### Help isloating the issue

- [ ] Did you tried to disabling some mixins in the mod config to see what mixin made the issue?
- [ ] Did you find what mixin made the issue?

### Game log

[latest.log](https://github.com/quentin452/OptimizationsAndTweaks/files/13997061/latest.log)

### Description

crash if all these mods are present together (omit any mod of these and the game still work properly):
your mod
falsepatternlib-mc1.7.10-1.0.0.jar
Et_Futurum_Requiem-2.5.1+nomixin.jar
archaicfix-0.7.0.jar
+unimixins-all-1.7.10-0.1.14.jar

**Comment by quentin452** [comment]
ok i see the original archaicfix is doesn't work with my mod , use my fork instead

**Comment by xdeadstokex** [comment]
> ok i see the original archaicfix is doesn't work with my mod , use my fork instead

yep, I see that bug in the other issue but it still work if I exclude ET-futurum, which is both odd and funny :)
(may I ask, are there chance that you contact with the other authors of performance mod such as archaicfix to make an official update of the mod, because I cant track all those bugfix fork, and maybe people will not open similar issue like this if they know the official bugfix)
