### ISSUE TITLE
[1.7.10]: Mod breaks Aether terrain

### ISSUE THREAD

**Issue by PopcornHead51** [quentin452/Multithreadingandtweaks#104]
### Help isloating the issue

- [ ] Did you tried to disabling some mixins in the mod config to see what mixin made the issue?
- [ ] Did you find what mixin made the issue?

### Game log

log was over 25 mb---could not upload.

### Description

When using recent versions of this mod, island terrain from Aether Legacy, Aether II: GOTV, and Aether Legacy Departure does not generate. Should the player spawn on an island, the island will generate, though it will be significantly smaller than most islands and will only be a few blocks in depth. Moving past that spawn island will again show no island terrain. This bug is present in the 1.12.6 version of the mod, though not the 1.11.5 version. I was having trouble setting up with intermediate versions, so I'm unsure when this bug was introduced.

![2024-01-20_11 55 53](https://github.com/quentin452/OptimizationsAndTweaks/assets/46089331/a62dc6b0-62cb-4023-bb26-798659b12f2c)
![2024-01-20_11 56 02](https://github.com/quentin452/OptimizationsAndTweaks/assets/46089331/8b0fd3f2-0e4d-4fa9-8241-f5d859f06e79)
![2024-01-20_11 56 18](https://github.com/quentin452/OptimizationsAndTweaks/assets/46089331/650a7ac7-7e5d-48bd-b398-9476437b2d9c)
![2024-01-20_12 08 34](https://github.com/quentin452/OptimizationsAndTweaks/assets/46089331/bd6ab726-0be9-4c17-b107-50689480bf22)

**Comment by quentin452** [comment]
for now disable "enableMixinNoiseGeneratorImproved" , the mixin will be removed soon due to redundant things
