### ISSUE TITLE
1.7.10:improve Flan mod entity performance (and fix bug)

### ISSUE THREAD

**Issue by xdeadstokex** [quentin452/Multithreadingandtweaks#106]
### Description

a lot of Flan mod entitys is too performance costly, it depends on the content creators effort on their model, so most of their model is high quality, like this: 
https://www.planetminecraft.com/mod/german-tanks-forge-1-7-10-flan-s-mod-content-pack/
here the mod git:
https://github.com/Unknown025/Flans-Mod-Plus
just a suggestion, you can skip it :D

**Comment by GamebP** [comment]
As modpack owner said before. Flans mod's and it's tanks, etc... make the modpack use more memory usage then it needs.

**Comment by quentin452** [comment]
when i try adding https://www.planetminecraft.com/mod/german-tanks-forge-1-7-10-flan-s-mod-content-pack/ and spawning tanks i crash so idk , i use https://www.curseforge.com/minecraft/mc-mods/flans-mod-ultimate-stability-edition

**Comment by xdeadstokex** [comment]
Im sorry that I not gave you a clear instruction:
https://www.curseforge.com/minecraft/mc-mods/flans-mod-ultimate-stability-edition/files/4389528
use this version (least bug)
https://www.planetminecraft.com/mod/german-tanks-forge-1-7-10-flan-s-mod-content-pack/
https://drive.google.com/file/d/1FWljTVvUBFlmJkyaqUUE9m7fxQd7UvQp/view?usp=sharing
use both of these content pack in order to make it working

and also, I found a bug with Flan and your mod, the bullet from guns instantly hit mob from any distant when you aim directly at a mob, regardless the travelling speed, but when you aim elsewhere, it run normally
here:https://drive.google.com/file/d/1KNzPLB4po6waEv7TaeRIPWSAmbsOfc49/view?usp=sharing
as the video point out, the panzerfault rocket has a low speed, but when i aim it at the creeper, it instant hit that mob

**Comment by xdeadstokex** [comment]
Relate to render, recommend to use render performence mod like angelia, so I will close this thread
