### ISSUE TITLE
1.7.10: subfolder mod load

### ISSUE THREAD

**Issue by xdeadstokex** [quentin452/Multithreadingandtweaks#107]
### Description

most of the time, any jar inside the subfolder inside the mod folder will not be loaded, so the idea is make forge load subfolder (very useful for SOME modpack creator, as not to dump all mods in a single folder without sorting, it would be a mess)
https://github.com/Chaos02/SubFolderLoader
the link above is the working mod implemented for 1.16.5 and above

**Comment by GamebP** [comment]
It isn't 1.7.10

**Comment by xdeadstokex** [comment]
like I say, this is a suggestion, I left the link there bc if imacatfr is going to do this,  imacatfr can at least have some references to begin with.



> It isn't 1.7.10

**Comment by HeatherComputer** [comment]
This also just isn't supported by most modpack loaders - you can't have them create subfolders within the mods folder, and most mods simply can't be distributed directly with the pack.

**Comment by xdeadstokex** [comment]
I suggest that it should be an auto off setting, if you want to turn it on, open the config folder
I never use modpack loader, I only install mods manually so when the mods list is way too big, it's hard to track which mod i want to replace or update without a sorting folder.
well, this suggestion may go no where :D

**Comment by HeatherComputer** [comment]
Huh. Why wouldn't you use a modpack loader?

**Comment by xdeadstokex** [comment]
> Huh. Why wouldn't you use a modpack loader?

because I have a lot of trust issue :D

real answer: 
who know what modpack loader do to your machines.
I dont like the Idea of installing another app just to get the game work as I want.
Most of the time, I have to reinstall my WIndow (for work), I dont want to lose my mods by forgetting where they're stored by those modpack loader or have to download these loaders again.
etc (I mean like a lot of other issues)
the end :D

**Comment by HeatherComputer** [comment]
They.. Run modpacks. That's about it really, especially with some of the more lightweight ones - some are FOSS too so you could even read the code and compile it yourself if you're that worried.

There's also a few that can do a "portable" installation which arguably leaves you with less stuff to worry about preserving when reinstalling windows


(as a side note, what job requires reinstalling windows often? Wouldn't a vm be a better option?}

**Comment by xdeadstokex** [comment]
> They.. Run modpacks. That's about it really, especially with some of the more lightweight ones - some are FOSS too so you could even read the code and compile it yourself if you're that worried.
> 
> There's also a few that can do a "portable" installation which arguably leaves you with less stuff to worry about preserving when reinstalling windows
> 
> (as a side note, what job requires reinstalling windows often? Wouldn't a vm be a better option?}

a vm does not guarantee that the machine will work with the same window installation, but that is another story, but hey, there are other issues with modpacks loader that I have met, let agree to disagree then, shall we, this little chat is starting to go randomly :D

(well I also test mods, like hundred of mods at the same time, so it would be great if I can separate them by folders, I dont want to change their name to sort though)

(somehow, MCheli work even if it is inside a subfolder if I recall correctly, how odd it is :> )

**Comment by HeatherComputer** [comment]
> a vm does not guarantee that the machine will work with the same window installation, but that is another story, but hey, there are other issues with modpacks loader that I have met, let agree to disagree then, shall we, this little chat is starting to go randomly :D
> 
What issues? I know of a few with the curseforge launcher, but a lot of those stem from it integrating the vanilla one. (I'm in this pack's discord if you want to chat there instead or something) 
> (well I also test mods, like hundred of mods at the same time, so it would be great if I can separate them by folders, I dont want to change their name to sort though)
> 
> (somehow, MCheli work even if it is inside a subfolder if I recall correctly, how odd it is :> )

I do recall 1.7.10 and 1.12 just loading mods from subfolders, so there's that.


As a side note.. If you download mods manually, what's the benefit to you if a pack even includes your suggested mod?

**Comment by xdeadstokex** [comment]
the issues is Im a pirate :D, Im poor as hell

the main benefit of "manual" is I know what i will do, I dont like "just pick any modpacks and play it", it's hard to describe by words.

**Comment by HeatherComputer** [comment]
> the issues is Im a pirate :D, Im poor as hell
> 
There are options for pirates that fit the above FOSS and portable descriptions I gave, but I don't fancy giving any links to them heh

**Comment by xdeadstokex** [comment]
yeah, I dont like pirating games though, if the game is good, I will support the authors, but the MOJANG we love is gone,I cant support the original indie game developers any more,any support will be taken by MicroSoft, I dont play above 1.12.2, I still watching MC update though, and as far as I know, MC is going downhill

**Comment by quentin452** [comment]
> ### Description
> 
> most of the time, any jar inside the subfolder inside the mod folder will not be loaded, so the idea is make forge load subfolder (very useful for SOME modpack creator, as not to dump all mods in a single folder without sorting, it would be a mess) https://github.com/Chaos02/SubFolderLoader the link above is the working mod implemented for 1.16.5 and above

this suggestion is good , i will see if i can do something :D

**Comment by quentin452** [comment]
it seem thats not possible using mixins, loaded too early issue and if i load the mixin late ,mods will be loaded before the mixin get injected

**Comment by xdeadstokex** [comment]
yep, I know it would be hard, but it is a fun suggestion though, thank for trying :)

**Comment by xdeadstokex** [comment]
Found a way to do this thing, so I will close this thread
