### ISSUE TITLE
[1.7.10] Crash with Aether or idk?

### ISSUE THREAD

**Issue by Starexify** [quentin452/Multithreadingandtweaks#108]
### Help isloating the issue

- [ ] Did you tried to disabling some mixins in the mod config to see what mixin made the issue?
- [ ] Did you find what mixin made the issue?

### Game log

https://pastebin.com/mGHb5EzG

### Description

I tried to run this in my own modpack and it crashes. I don't know the cause really, but I know this mod just crashes.

**Comment by quentin452** [comment]
what jar of aether you use?

**Comment by quentin452** [comment]
hum i see ,you use two aether :D

The aether and aether 2

you should use The eather

**Comment by Starexify** [comment]
So Aether 2 is not supported by this mod?

**Comment by Starexify** [comment]
> hum i see ,you use two aether :D
> 
> The aether and aether 2
> 
> you should use The eather

So Aether 2 is not supported by this mod?

**Comment by quentin452** [comment]
Aether 1 and Aether 2 don't had same packages name , my mod support only aether 1 , or you need to disable all aether mixins in configs
