### ISSUE TITLE
1.7.10: superflat is not flat

### ISSUE THREAD

**Issue by xdeadstokex** [quentin452/Multithreadingandtweaks#114]
### Game log

none

### Description

that all
![image](https://github.com/quentin452/OptimizationsAndTweaks/assets/129391255/9d5940ea-a892-4bd7-8db9-2c73df1c2eb9)
existed superflat+ bug generation (kind of cool, i guess)
![image](https://github.com/quentin452/OptimizationsAndTweaks/assets/129391255/ed7e6f57-f1f1-4845-b0f3-bce8cbe9bbad)

**Comment by quentin452** [comment]
i found which mixin causing the issue : MixinWorldType , so you need to disabling it for now if you want to use Flat worldtype
