### ISSUE TITLE
Falsetweaks Crash on startup

### ISSUE THREAD

**Issue by iamsoNewBee** [quentin452/Multithreadingandtweaks#12]
### Description

<img width="396" alt="image" src="https://user-images.githubusercontent.com/98573273/236651611-07640226-713d-46f0-b3b4-3dc9611db757.png">
NO [UniMixins] ? IS IT RIGHT?

**Comment by quentin452** [comment]
not a problem with Gasstation , its a problem with falsetweaks

**Comment by iamsoNewBee** [comment]
but i can run it without any crash

**Comment by iamsoNewBee** [comment]
??????

**Comment by quentin452** [comment]
me i can run it with gasstation

**Comment by quentin452** [comment]
its not a crash caused by gasstation , its caused by an incompat between multithreading and tweaks and falsetweaks

**Comment by iamsoNewBee** [comment]
strange

**Comment by quentin452** [comment]
for now you can disabling voxelizer from falsetweaks

**Comment by iamsoNewBee** [comment]
one suipid question:so i can run  Multithreadingandtweaks without UniMixins .right?and i didnt crash with these mods but i meet crash when i use unimixins.

**Comment by quentin452** [comment]
> one suipid question:so i can run Multithreadingandtweaks without UniMixins .right?and i didnt crash with these mods but i meet crash when i use unimixins.

You don't know ? that unimixin is like gasstation , its a mixin loader you can't run theses two mods at once

**Comment by iamsoNewBee** [comment]
when i use unimixin i deleted gasstation

**Comment by iamsoNewBee** [comment]
i also opened issue about that mod

**Comment by quentin452** [comment]
whats the crash report?

**Comment by iamsoNewBee** [comment]
https://github.com/LegacyModdingMC/UniMixins/issues/11

**Comment by quentin452** [comment]
so i maked some tests and it seem that cannot be fixed in multithreading side , lets try to change the source code from falsetweaks

**Comment by quentin452** [comment]
Fox now I don't know whats the problem , i just know what class cause the problem , but idk why

**Comment by quentin452** [comment]
i will make an issue on falsetweaks side

**Comment by iamsoNewBee** [comment]
u crash when u add multi adn falsetweaks?

**Comment by quentin452** [comment]
its caused by TRIANGULATOR , but idk how to fix

**Comment by iamsoNewBee** [comment]
i dont know why i dont crash.confusing and i dont konw where is your problem(??)

**Comment by quentin452** [comment]
for the clarity , the game crash if you have multithreading and tweaks and falsetweaks enabled with triangulator enabled from falsetweaks

**Comment by quentin452** [comment]
fixed by updating falsepatternlib
