### ISSUE TITLE
[1.7.10]: world create crash (probably after d3408ea)

### ISSUE THREAD

**Issue by kotmatross28729** [quentin452/Multithreadingandtweaks#13]
### Modpack

Custom

### Game log

Pastebin:

Crash 1 (java.lang.IllegalStateException: TickNextTick list out of synch) : https://pastebin.com/Cc50Yfub

Crash 2 (java.util.ConcurrentModificationException) : https://pastebin.com/4gX2PSLc

Log:

[fml-client-latest.log](https://github.com/quentin452/Multithreadingandtweaks/files/11469415/fml-client-latest.log)

### Description

When trying to create a world with a new version
Multithreadingandtweaks (d3408ea) game crashes with error
Looks like it's something is out of sync

By the way, there are 2 types of crash:

[java.util.ConcurrentModificationException](https://pastebin.com/4gX2PSLc)

[java.lang.IllegalStateException: TickNextTick list out of synch](https://pastebin.com/Cc50Yfub)

**Comment by quentin452** [comment]
its normal not finished
