### ISSUE TITLE
[1.7.10]: after update V0.8.7.3 client side not starting

### ISSUE THREAD

**Issue by ptk2003** [quentin452/Multithreadingandtweaks#17]
### Game log

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: powercrystals/minefactoryreloaded/world/WorldGenRubberTree
[crash-2023-09-06_14.14.01-client.txt](https://github.com/quentin452/Multithreadingandtweaks/files/12536762/crash-2023-09-06_14.14.01-client.txt)

### Description

after update from multithreadingandtweaks-V0.8.6.4.jar to multithreadingandtweaks-V0.8.7.3.jar
client side not starting, in crash-report error loading MFR 
(server side not trying update)

forge:1.7.10-10.13.4.1614

+unimixins-all-1.7.10-0.1.11.jar
falsepatternlib-mc1.7.10-0.12.1.jar

MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar
CoFHCore-[1.7.10]3.1.4-329.jar
CoFHLib-[1.7.10]1.2.1-185.jar

**Comment by quentin452** [comment]
its really weird for me its working

**Comment by quentin452** [comment]
Try resetting config

**Comment by ChromaPIE** [comment]
got a similar clientside crash on startup using reuploaded 0.8.7.4.1, crash report: 
[crash-2023-09-09_03.21.54-client.txt](https://github.com/quentin452/Multithreadingandtweaks/files/12563036/crash-2023-09-09_03.21.54-client.txt)

**Comment by quentin452** [comment]
> got a similar clientside crash on startup using reuploaded 0.8.7.4.1, crash report: [crash-2023-09-09_03.21.54-client.txt](https://github.com/quentin452/Multithreadingandtweaks/files/12563036/crash-2023-09-09_03.21.54-client.txt)

it seem that hte crash with pam harvestcraft you got it because you use harvescraft GTNH

**Comment by ptk2003** [comment]
?
i have not pam harvestcraft
redownload not solved issue too

**Comment by ChromaPIE** [comment]
@ptk2003 im using GTNH 2.4.0, with several self-added optimizing mods, you can check my modlist to see if it helps with your further diagnosis.

**Comment by ChromaPIE** [comment]
@quentin452 listen bro i just wanna thank you for your mod its literally more than saving life. the version of the game was long cursed by framerate drops when moving around. in my GTNH instance it drops to 30-40 by doing literally nothing but just moving around, now i got steady 60 (maybe even more bc i set a framerate cap at 60), and with complementary shaders shaderpack on its a steady 50, totally playable. this is fucking amazing thank you!

**Comment by quentin452** [comment]
> ? i have not pam harvestcraft redownload not solved issue too

Can you give a new crash report

**Comment by ptk2003** [comment]
after redownloading multithreadingandtweaks-V0.8.7.3.jar

[crash-2023-09-06_17.25.37-client.txt](https://github.com/quentin452/Multithreadingandtweaks/files/12566611/crash-2023-09-06_17.25.37-client.txt)

**Comment by ptk2003** [comment]
after downloading multithreadingandtweaks-V0.8.7.5hotfix.jar
[crash-2023-09-09_23.13.38-client.txt](https://github.com/quentin452/Multithreadingandtweaks/files/12566613/crash-2023-09-09_23.13.38-client.txt)

**Comment by ptk2003** [comment]
after removed all other mods for test, still only:
+unimixins-all-1.7.10-0.1.11.jar
CoFHCore-[1.7.10]3.1.4-329.jar
CoFHLib-[1.7.10]1.2.1-185.jar
cofh_MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar
falsepatternlib-mc1.7.10-0.12.1.jar
multithreadingandtweaks-V0.8.7.5hotfix.jar



[crash-2023-09-09_23.16.43-client.txt](https://github.com/quentin452/Multithreadingandtweaks/files/12566615/crash-2023-09-09_23.16.43-client.txt)

**Comment by quentin452** [comment]
hum i see the issue , remove cofh_ at the start of the minefactory reloaded jar

**Comment by ptk2003** [comment]
nothing change. config multi and falsepattern i removed too
C:\Windows\system32>dir /b C:\Users\admin\AppData\Roaming\.minecraft\mods
+unimixins-all-1.7.10-0.1.11.jar
CoFHCore-[1.7.10]3.1.4-329.jar
CoFHLib-[1.7.10]1.2.1-185.jar
falsepatternlib-mc1.7.10-0.12.1.jar
MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar
multithreadingandtweaks-V0.8.7.5hotfix.jar

**Comment by quentin452** [comment]
try removing cofh lib , if it not fixed , there is no fix i think

**Comment by ptk2003** [comment]
Sorry, I didn't quite understand, do I need to remove the mod library? for what? MFR demands it

--
upd: As expected, the mod won't launch without the library.
Time: 09.09.23 23:29
Description: Initializing game

Missing Mods:
	null : ThermalExpansion

cpw.mods.fml.common.MissingModsException

**Comment by quentin452** [comment]
CoFHLib isn't needed but thermal expansion + thermal foundation + cofhcore its needed

Has a workaround to fix the crash you can disable "enableMixinFixRubberTreesMinefactoryReloadedCascadingWorldgenFix" in multithreadingandtweaks

**Comment by ptk2003** [comment]
really, CoFHLib required by MFR only if TE+TF not present, after remove this and rename file MFR, modpack started.
Thank you.
