### ISSUE TITLE
[1.7.10]: Crash on startup ( 0.8.7.7 ) 

### ISSUE THREAD

**Issue by Omgise** [quentin452/Multithreadingandtweaks#19]
### Game log

[fml-client-latest.log](https://github.com/quentin452/Multithreadingandtweaks/files/12575539/fml-client-latest.log)

### Description

no desc

**Comment by quentin452** [comment]
its a bug caused by harvestthenether , you need to add minefactory reloaded to the pack or removing harvestthenether

**Comment by Omgise** [comment]
The crash disappeared after removing Harvestthenether.
Thank you.
