### ISSUE TITLE
[1.7.10]: Crash with HBM

### ISSUE THREAD

**Issue by kotmatross28729** [quentin452/Multithreadingandtweaks#20]
### Game log

there is no point in the logs, since there is nothing important there, a crash report appears:
https://pastebin.com/YLde1Jp2

### Description

I can’t say for sure that it’s multithreadingandtweaks fault yet, but in the staktrace the first thing listed is `handler$zcj000$multithreadingandtweaks$onNewExplosion`
maybe tomorrow I can test it for sure, for now I can say that I spawned a lot of Taint crabs (maybe 25 - 30) to test the artillery, but the game crashed

**Comment by quentin452** [comment]
Can you try this new build?
https://mega.nz/file/et0jUTBZ#g3JUhrDU0lrHwfR6FRNWBiQY6z7_yPZhZ0922fE2SX4

**Comment by kotmatross28729** [comment]
tried it, still crash: https://pastebin.com/dsTUNSYu (same)

**Comment by kotmatross28729** [comment]
also managed to reproduce without other mods, only hbm + Multithreadingandtweaks (falsepatternlib, unimixins).
Without Multithreadingandtweaks, there is no crash

**Comment by quentin452** [comment]
for now you could disabling the mixin "enableMixinExplosions" in configs
