### ISSUE TITLE
[1.7.10]:crash when game start 

### ISSUE THREAD

**Issue by Oldmemory1** [quentin452/Multithreadingandtweaks#21]
### Game log

https://pastebin.com/AnEsBTdm

### Description

It is very strange ,I use Minefactory Reloaded Latest Version and harvestCraft Latest Version. After I removed Multithreadingandtweaks,It does not crash.
In addition,changed to GTNH version harvestCraft also caused this type crash

**Comment by quentin452** [comment]
normally you shouldn't crash , so wont fix, the only one thing you can make is to disable mixins from MFR/harvestcraft in multithreading and tweaks

I already maked something that normally fix it , but idk why for some people is doesn't work

**Comment by quentin452** [comment]
But maybe you could watch the last message in this issue , https://github.com/quentin452/Multithreadingandtweaks/issues/17

**Comment by Oldmemory1** [comment]
> But maybe you could watch the last message in this issue , #17

I have tried ,It can be fixed by disable mfr/harvestcraft mixins config.

**Comment by quentin452** [comment]
but it seem thats you use an old version of MFR

**Comment by quentin452** [comment]
latest : https://www.curseforge.com/minecraft/mc-mods/minefactory-reloaded/files/2366149

**Comment by Oldmemory1** [comment]
Yeah,I have change to MFR 2.8.2B1-201  Pam's HarvestCraft 1.7.10Lb,but It doesn't work unless I change mixins configuration...

**Comment by quentin452** [comment]
So for now unless i can reproduce the issue , the issue will be wontfixed

**Comment by quentin452** [comment]
Can you try updating mfr compat to https://legacy.curseforge.com/minecraft/mc-mods/magical-crops-compat-minefactory-reloaded/files/2362956
