### ISSUE TITLE
[TYPE THE MC VERSION]: 1.7.10 odd bug or critical issue with v0.8.9.1

### ISSUE THREAD

**Issue by ghost** [quentin452/Multithreadingandtweaks#22]
### Modpack

custom

### Game log

[latest.log](https://github.com/quentin452/Multithreadingandtweaks/files/13042592/latest.log)

### Description

![2023-10-19_17 21 08](https://github.com/quentin452/Multithreadingandtweaks/assets/139335984/e57c6a52-3de3-4151-9dc7-029273afeb11)
i don't know how to describe it
hand is looking weird
i can't move
when i jump, i starting flying in creative mode

**Comment by ghost** [comment]
![2023-10-19_17 32 24](https://github.com/quentin452/Multithreadingandtweaks/assets/139335984/ca35b703-7a6f-4340-8869-18efa49ef32d)
another one example of this bug

**Comment by quentin452** [comment]
infact i just gave the wrong file so l'ill reupload it ,fixed

**Comment by quentin452** [comment]
https://github.com/quentin452/Multithreadingandtweaks/releases/tag/V0.8.9.1
