### ISSUE TITLE
[1.7.10]: Crash with FalseTweaks

### ISSUE THREAD

**Issue by kotmatross28729** [quentin452/Multithreadingandtweaks#23]
### Game log

https://pastebin.com/8SxumWTB

### Description

If your modpack has FalseTweaks, then, if you add Multithreadingandtweaks , game will crash

**Comment by quentin452** [comment]
can you try this?https://mega.nz/file/m1FjnABI#pZ9PNFxYqqKz1tDtY9qE3gwcjtqjV8-9imTr1kiv9Vw
