### ISSUE TITLE
[1.7.10]: Invisible skin (in some cases a hand) with shaders

### ISSUE THREAD

**Issue by kotmatross28729** [quentin452/Multithreadingandtweaks#26]
### Game log

.

### Description

without Multithreadingandtweaks:
![2023-10-19_22 49 00](https://github.com/quentin452/Multithreadingandtweaks/assets/110309314/966f12fe-cd68-45f5-8b99-5cafdc39442d)

with Multithreadingandtweaks:

![2023-10-19_22 50 47](https://github.com/quentin452/Multithreadingandtweaks/assets/110309314/dd292bf6-03f6-48ea-a17f-eacfc6ae1391)

to reproduce:
Multithreadingandtweaks (+ dependencies), optifine, any shaders.
go into the world, turn on 3rd person view (or notice that you don't have a 1st person hand) - > bug

**Comment by quentin452** [comment]
for now you could disabling enableMixinModelRenderer

**Comment by quentin452** [comment]
fixed in dev build
