### ISSUE TITLE
Incompat between voxelizer from falsetweaks and Multithreadingandtweaks

### ISSUE THREAD

**Issue by kotmatross28729** [quentin452/Multithreadingandtweaks#3]
btw, mod for some reason reduces fps, any idea why? (xeon e5 2620 v3)

https://user-images.githubusercontent.com/110309314/235344450-0d6785c2-37d3-4a4e-a023-e45b8c1fd65c.mp4

**Comment by quentin452** [comment]
Do you have a world ?

**Comment by kotmatross28729** [comment]
[New World.zip](https://github.com/quentin452/Multithreadingandtweaks/files/11360925/New.World.zip)

**Comment by quentin452** [comment]
> [New World.zip](https://github.com/quentin452/Multithreadingandtweaks/files/11360925/New.World.zip)

give me the location

**Comment by kotmatross28729** [comment]
-697 50 70

**Comment by quentin452** [comment]
it seem i don't have the bug , can you give me the config folder?

**Comment by kotmatross28729** [comment]
[config.zip](https://github.com/quentin452/Multithreadingandtweaks/files/11360947/config.zip)
[mods.zip](https://github.com/quentin452/Multithreadingandtweaks/files/11360948/mods.zip)

**Comment by quentin452** [comment]
ok it seem i have the problem , so i guess a config incompat , i will try to find out

**Comment by kotmatross28729** [comment]
What about performance? fps with this mod is lower than without it. Or lower fps to make tps higher? Can you explain if you don't mind?

**Comment by quentin452** [comment]
so ok i find the problem : its the voxelizer in falsetweaks and i suggest to you to disabling MixinEntityUpdate and MixinEntityAITask because theses settings are bugged and can use more tps right now

**Comment by quentin452** [comment]
for my test i have 1600 fps without multithreading and tweask and 1900 fps with it at same location

> What about performance? fps with this mod is lower than without it. Or lower fps to make tps higher? Can you explain if you don't mind?

**Comment by quentin452** [comment]
and i get a bit better tps , but the mod is really bugged , i maked it 1 or 2 days ago :D

**Comment by quentin452** [comment]
In the next release i will reenabling EntityAITask and EntityUpdate and i will add more features , for now i will add a config to change the number of threads of features( i things your fps bugs come from here)

**Comment by quentin452** [comment]
So i maked an artifact with, but all times i make artifact on github , the artifact is doesn't work

Add a config to change the number of threads of features

Add mixinchunkpopulating and mixinlightningengine to multithreading

fix some bugs

**Comment by quentin452** [comment]
it seem that the bug isn't caused by multithreadingandtweaks even with the mod disabled i have the bug with falsetweaks

**Comment by kotmatross28729** [comment]
yes, I have already reported this : https://github.com/FalsePattern/FalseTweaks/issues/103
