### ISSUE TITLE
[1.7.10]: Game creating too many treads

### ISSUE THREAD

**Issue by Tiago-o-Oliveira** [quentin452/Multithreadingandtweaks#30]
### Modpack

personal

### Game log

[Uploading fml-client-latest.log…](Log)

### Description

First things first, please apologize me if i explain something wrong, I'm not very used to java technical therms.
The thing here seems to be this, with the latest mod version installed, whenever the game loads a chunk (doesn't need to be a new chunk) the game creates a immense amount of threads, as seen [here](https://github.com/quentin452/Multithreadingandtweaks/assets/116642713/a14d3318-4210-4e61-9157-bedfba28cd63), this leads to a crash [:)](https://github.com/quentin452/Multithreadingandtweaks/files/13061830/crash-2023-10-21_17.55.25-server.txt) in just couple minutes of playing.

**Comment by quentin452** [comment]
your logs is doesn't work , pls reupload

**Comment by quentin452** [comment]
this version should fix your issue https://mega.nz/file/jw9mUBDA#BEy5a1OQQ6ZxkPptU-fEtakqVmbiF3lnLffnjZ4-SIY
