### ISSUE TITLE
[1.7.10]: Game crash

### ISSUE THREAD

**Issue by Omgise** [quentin452/Multithreadingandtweaks#33]
### Game log

[fml-client-latest.log](https://github.com/quentin452/Multithreadingandtweaks/files/13065645/fml-client-latest.log)

### Description

Collapses upon entering the world

**Comment by quentin452** [comment]
Can you try this : https://mega.nz/file/ak9U3Kxa#TOnCfz3-weZoKrRmutqrJkdxli39T6pKOwOhYkzND00

**Comment by Omgise** [comment]
The game still crashes
[fml-client-latest.log](https://github.com/quentin452/Multithreadingandtweaks/files/13065734/fml-client-latest.log)

**Comment by quentin452** [comment]
new dev build : https://mega.nz/file/v5USSSzI#SM7FKYokcKE8OcWsHg2HJVWJtk5eb9MlahhibWbSVFQ

**Comment by Omgise** [comment]
The game no longer crashes, thanks
