### ISSUE TITLE
[1.7.10]: Incompatible with SkinPort

### ISSUE THREAD

**Issue by Omgise** [quentin452/Multithreadingandtweaks#34]
### Game log

null

### Description

![image](https://github.com/quentin452/Multithreadingandtweaks/assets/106000018/fa20959b-9e78-4913-b1e4-e09c9dcc49dd)

**Comment by Omgise** [comment]
After removing Multithreadingandtweaks, the skin renders normally
![image](https://github.com/quentin452/Multithreadingandtweaks/assets/106000018/6743e709-67c4-4de7-aa48-62a865730e35)

**Comment by quentin452** [comment]
Fixed in V0.9.0.7
