### ISSUE TITLE
[1.7.10]: Game crashing on GTNH2.4.1 caused by MixinEntityVillageGuard(probably a third party compat)

### ISSUE THREAD

**Issue by chixiguaya** [quentin452/Multithreadingandtweaks#37]
### Modpack

GTNH2.4.1

### Game log

[fml-client-latest.log](https://github.com/quentin452/OptimizationsAndTweaks/files/13113394/fml-client-latest.log)

### Description

I can use V1.0,but later versions seem to be unable to enter the game.
My launcher indicates that my crash seems to be related to the witchery mod.
<img width="643" alt="{F0BCC73F-8F9C-4314-89E1-343E407FEADA}" src="https://github.com/quentin452/OptimizationsAndTweaks/assets/128808795/f63632bc-4fef-4bd3-8de3-7efcf787b122">

**Comment by quentin452** [comment]
can you try : https://mega.nz/file/a0shBIwK#kDkZKQmo1dKEaHqb2lpJRWFcbqGRE7n98LR-kcZbG6g

**Comment by chixiguaya** [comment]
[fml-client-latest.log](https://github.com/quentin452/OptimizationsAndTweaks/files/13113547/fml-client-latest.log)
There's no difference

**Comment by quentin452** [comment]
so you need to disable MixinEntityVillageGuard in config of optimizationsandtweaks

**Comment by chixiguaya** [comment]
Okay, I got it

**Comment by quentin452** [comment]
where/how did you downloaded GTNH2.4.1

**Comment by chixiguaya** [comment]
i downloaded GTNH2.4.1 on http://downloads.gtnewhorizons.com/Multi_mc_downloads/.
To improve the experience for me and my friends
I have added some mods, most of which are optimized mods for 1.7.10 recommended by others.
Perhaps these optimized mods have caused some conflicts.
<img width="552" alt="捕获" src="https://github.com/quentin452/OptimizationsAndTweaks/assets/128808795/fb5b7e01-8450-4c9c-b7a5-aabbf68bb47c">
These are the mods I added.

**Comment by quentin452** [comment]
ok l'ill try later :D

**Comment by chixiguaya** [comment]
Furthermore, I can't remember clearly. Since a certain version, the functionality of my F7 and F9 seems to have stopped working properly

**Comment by chixiguaya** [comment]
There seems to be some issues with the display brightness level

**Comment by chixiguaya** [comment]
It is still normal in version 0.8.8.7

**Comment by quentin452** [comment]
can you give to me a import of the modpack?

**Comment by chixiguaya** [comment]
Okay. But since I am in China,  uploading will take some time.

**Comment by quentin452** [comment]
Can you try this? https://mega.nz/file/utcVzRhA#jQW0eBxSjVXUQLsu0iLOhZrb5BX1W5XFLT8uWV8pBHE

**Comment by chixiguaya** [comment]
modpack:https://drive.google.com/file/d/1VpAjTOcFkjPk-meUWDPZm9Yf77vyVL8c/view?usp=sharing

**Comment by quentin452** [comment]
ok thx

**Comment by chixiguaya** [comment]
There is another new issue that will now report an error with the ASMC mod.

**Comment by chixiguaya** [comment]
![image](https://github.com/quentin452/OptimizationsAndTweaks/assets/128808795/c109cf2b-a390-43d9-88f0-359a7864805b)

**Comment by quentin452** [comment]
maybe you should make an issue report into my fork of ASMC https://github.com/quentin452/Asmc-Fork

**Comment by quentin452** [comment]
> Can you try this? https://mega.nz/file/utcVzRhA#jQW0eBxSjVXUQLsu0iLOhZrb5BX1W5XFLT8uWV8pBHE

did you tried this dev build?

**Comment by chixiguaya** [comment]
![image](https://github.com/quentin452/OptimizationsAndTweaks/assets/128808795/2849d1d7-2f05-4a9f-aab1-bc31f7c4d7b9)
After using your ASMC work, the game no longer crashes.
After using dev build, my F7 function works normally on the surface, but it doesn't work in caves.

**Comment by chixiguaya** [comment]
![image](https://github.com/quentin452/OptimizationsAndTweaks/assets/128808795/6597d763-49fd-4675-a9e6-1ebc295264e6)
If I move forward, the red fork will move back

**Comment by quentin452** [comment]
it seem thats not a bug caused by Optimizationsandtweaks
