### ISSUE TITLE
[1.7.10]: crash with Blendtronic and hbm/cofhcore/ZPM2 (NoClassDefFoundError)

### ISSUE THREAD

**Issue by kotmatross28729** [quentin452/Multithreadingandtweaks#38]
### Game log

https://pastebin.com/5w4PRSVK

### Description

if you have: 

1) OptimizationsAndTweaks (+ dependencies), 
2) [Blendtronic](https://github.com/GTMEGA/Blendtronic), 
3) and any of these mods ([hbm](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT), [cofhcore](https://www.curseforge.com/minecraft/mc-mods/cofh-core/files?page=1&pageSize=20&version=1.7.10) or [Zombie Plague Mod 2](https://legacy.curseforge.com/minecraft/mc-mods/forge-zombie-plague-mod-2-wip)),

 the game will crash (I think this has nothing to do with these 3 specific mods, rather it has to do with anything that does anything with the generation `(java.lang.NoClassDefFoundError: net/minecraft/world/chunk/Chunk)`, but not sure)

**Comment by quentin452** [comment]
can you try the 1.1.0?

**Comment by kotmatross28729** [comment]
I tried it now, with 1.1.0 it still crashes

**Comment by kotmatross28729** [comment]
still crashes with 1.1.1 : https://pastebin.com/pF3gEEqr

**Comment by kotmatross28729** [comment]
> still crashes with 1.1.1 : https://pastebin.com/pF3gEEqr

fixed in 1.1.2
