### ISSUE TITLE
[1.7.10]: crash with netherlicious (NoClassDefFoundError), only in modpack (202 mods)

### ISSUE THREAD

**Issue by kotmatross28729** [quentin452/Multithreadingandtweaks#40]
### Modpack

Custom

### Game log

https://pastebin.com/JqRXjLTC

### Description

I don’t know exactly why, but only with netherlicious and OptimizationsAndTweaks it starts, but it gives an crash in the modpack:
`method func_75295_a in mixins.optimizationsandtweaks.json:common.core.MixinEntityAITarget cannot reduce visibiliy of PROTECTED target method`

**Comment by quentin452** [comment]
could you try this? https://mega.nz/file/P0F0hDoA#L4BI6Vd1prDcSWU0Lur5SE88RdTpaBKEsEhBlQ1o8oc

**Comment by kotmatross28729** [comment]
> could you try this? https://mega.nz/file/P0F0hDoA#L4BI6Vd1prDcSWU0Lur5SE88RdTpaBKEsEhBlQ1o8oc

Yes, this fixed the problem, thanks!
