### ISSUE TITLE
[1.7.10]: Game crash

### ISSUE THREAD

**Issue by Omgise** [quentin452/Multithreadingandtweaks#42]
### Game log

[fml-client-latest.log](https://github.com/quentin452/OptimizationsAndTweaks/files/13176657/fml-client-latest.log)

### Description

null

**Comment by quentin452** [comment]
can you try this ? : https://mega.nz/file/ntV2BL5B#GGA3jnBG_IZlChgKVvW3fi53JolCY169MUriGumrdrs

**Comment by Omgise** [comment]
Ok, this version fixes this crash and the game works just fine, thanks
