### ISSUE TITLE
[1.7.10]: Crash with hbm (specific place)

### ISSUE THREAD

**Issue by Darek505** [quentin452/Multithreadingandtweaks#43]
### Modpack

My own

### Game log

Crash report: https://pastebin.com/ErpF4Mwk (NullPointerException. something with RenderGlobal, EntityRenderer, etc...)

### Description

According to my tests, this happens ONLY when you approach **this** (see below) building (in **this** exact location):
![2023-10-26_18 03 40](https://github.com/quentin452/OptimizationsAndTweaks/assets/122032896/b373786b-bf8d-4b87-b142-048e501d2495)

![2023-10-26_18 03 46](https://github.com/quentin452/OptimizationsAndTweaks/assets/122032896/61f39b59-feb8-4878-ad31-1103e4008420)

if there is no optimizationsandtweaks, then this crash does not happen. also, in this case the entire screen freezes and becomes one color (blue, white, gray)

**Comment by kotmatross28729** [comment]
@Darek505, I told you to wait until I check it myself, before reporting. And try 1.1.5, it fixed crash for me.
Also, go to discord

**Comment by Darek505** [comment]
Did you check this in the modpack?

**Comment by kotmatross28729** [comment]
Yes

**Comment by Darek505** [comment]
Ah, ok
