### ISSUE TITLE
[1.7.10]: Crash with Witchery

### ISSUE THREAD

**Issue by Tiago-o-Oliveira** [quentin452/Multithreadingandtweaks#45]
### Modpack

Personal

### Help isloating the issue

- [X] Did you tried to disabling some mixins in the mod config to see what mixin made the issue?
- [X] Did you find what mixin made the issue?

### Game log

[crash-2023-10-26_21.16.30-client.txt](https://github.com/quentin452/OptimizationsAndTweaks/files/13183823/crash-2023-10-26_21.16.30-client.txt)

### Description

Not sure if this is the same bug as #37, but i'm the game is crashing with enableMixinEntityVillageGuard set to true, disabling it solves the problem, i've also tested on the latest dev build and the error persists.

**Comment by quentin452** [comment]
i don't have clues

**Comment by quentin452** [comment]
you just need to disable enableMixinEntityVillageGuard

**Comment by quentin452** [comment]
sometimes this issue appear and sometimes not ,and this bug appear never in certain modpack so idk

**Comment by quentin452** [comment]
so maybe i should remove this mixin

**Comment by Tiago-o-Oliveira** [comment]
or default it to false maybe

**Comment by chixiguaya** [comment]
After I use the latest version，i enable enableMixinEntityVillageGuard and it works.During this period, I only changed ASMC and OptimizationsAndTweaks version.

**Comment by quentin452** [comment]
@Tiago-o-Oliveira  ah yeah i see, you use ptimizationsandtweaks-V1.1.7-1-7-10.4+be55090a2e-dirty, you should try updating to the release

**Comment by quentin452** [comment]
in all case , i maked a workaround for it , i removed the Witchery mixin and added an another mixin that don't touch Witchery
