### ISSUE TITLE
[1.7.10]: Crash with web block (java.lang.NullPointerException: Colliding entity with block)

### ISSUE THREAD

**Issue by kotmatross28729** [quentin452/Multithreadingandtweaks#47]
### Help isloating the issue

- [X] Did you tried to disabling some mixins in the mod config to see what mixin made the issue?
- [x] Did you find what mixin made the issue?

### Game log

https://pastebin.com/gT2M5KX1

### Description

To reproduce, place a web block and go into it (if only oat + dependencies are installed, then it takes 2-3 seconds to crash, in a larger modpack it crashes instantly

EDIT: found the mixin causing the problem: MixinEntity (enableMixinEntity)
if `B:enableMixinEntity=false`, then the game doesn't crash

**Comment by quentin452** [comment]
This version should fix #47 #46 :  https://mega.nz/file/motXkYxb#V0dyLn7NtegH5BZOjP1UydCDliP0QalSq47EfoFIKjQ
