### ISSUE TITLE
[1.7.10]: Crashes while starting the game

### ISSUE THREAD

**Issue by Omgise** [quentin452/Multithreadingandtweaks#48]
### Help isloating the issue

- [ ] Did you tried to disabling some mixins in the mod config to see what mixin made the issue?
- [ ] Did you find what mixin made the issue?

### Game log

[fml-client-latest.log](https://github.com/quentin452/OptimizationsAndTweaks/files/13193998/fml-client-latest.log)

### Description

Maybe MixinPathNavigate caused the problem

**Comment by quentin452** [comment]
could you try this? https://mega.nz/file/a5sAhIqI#t_rOLKVyAQQaGMfWJ3cTmVPeSnPEjOUsmd7DHoPisfE

**Comment by quentin452** [comment]
so the thumb's up , signify its fixed?

**Comment by Omgise** [comment]
> so the thumb's up , signify its fixed?

No, the game is still crashing
[fml-client-latest.log](https://github.com/quentin452/OptimizationsAndTweaks/files/13194018/fml-client-latest.log)

**Comment by quentin452** [comment]
ok now its an another method that make the issue , i will give to you a new dev build

**Comment by quentin452** [comment]
https://mega.nz/file/2ocxxZpT#lP_UCmoM66zFmoVS75_PwJLrcRrA6TV8hfjXl_Ac-1Y

**Comment by Omgise** [comment]
[fml-client-latest.log](https://github.com/quentin452/OptimizationsAndTweaks/files/13194024/fml-client-latest.log)

**Comment by quentin452** [comment]
bruh again an another method ....

**Comment by quentin452** [comment]
https://mega.nz/file/q0NyDALS#bCaw9QmRdIJzGMFy7NR0gw_xyJXV1fr8RW7mfHz5LoE

**Comment by Omgise** [comment]
[fml-client-latest.log](https://github.com/quentin452/OptimizationsAndTweaks/files/13194030/fml-client-latest.log)

**Comment by quentin452** [comment]
https://mega.nz/file/Dx0GCSqC#3dIANZS_adMM2EIZqKHOgxMV8fU2AjK9GEM6yAErYgU

**Comment by Omgise** [comment]
Yes, this version fixes the crash
