### ISSUE TITLE
[1.7.10]: Crashes when creating worlds

### ISSUE THREAD

**Issue by Omgise** [quentin452/Multithreadingandtweaks#50]
### Help isloating the issue

- [ ] Did you tried to disabling some mixins in the mod config to see what mixin made the issue?
- [X] Did you find what mixin made the issue?

### Game log

[fml-client-latest.log](https://github.com/quentin452/OptimizationsAndTweaks/files/13204419/fml-client-latest.log)

### Description

`MixinEntityLivingUpdate`  `MixinEntityLiving`  `MixinWorld`  `MixinEntityAgeable`  `MixinEntityAnimal`

It should be their few mixins that cause the problem

**Comment by quentin452** [comment]
where did you downloaded DrZharks.MoCreatures.Mod.v6.3.2?

**Comment by Omgise** [comment]
> where did you downloaded DrZharks.MoCreatures.Mod.v6.3.2?

https://github.com/jss2a98aj/mocreaturesdev

**Comment by quentin452** [comment]
ok ,so for me the crash is unreproducable  , i tried adding optimizations and tweaks and mocreatures but i don't have the crash , so i think its an incompat with an another mod

**Comment by Omgise** [comment]
This is the crash log generated after deleting mocreatures

[fml-client-latest.log](https://github.com/quentin452/OptimizationsAndTweaks/files/13205426/fml-client-latest.log)

**Comment by quentin452** [comment]
does the crash appear without optimizationsandtweaks?

**Comment by Omgise** [comment]
no

**Comment by Omgise** [comment]
OptimizationsAndTweaks from version 1.2.3 onwards, the game crashes when entering the game when creating the world

**Comment by quentin452** [comment]
can you try disabling MixinMinecraftServer?

**Comment by Omgise** [comment]
Ok, I'll try

**Comment by Omgise** [comment]
[fml-client-latest.log](https://github.com/quentin452/OptimizationsAndTweaks/files/13205613/fml-client-latest.log)

**Comment by quentin452** [comment]
Its possible to give your minecraft instance to make tests on my end?

**Comment by Omgise** [comment]
Of course you can

**Comment by Omgise** [comment]
https://www.dropbox.com/scl/fi/gcjhxb7xvwxo6eafiofhb/1.7.10-Eaminewetre.7z?rlkey=ghoq2lbk0n4tgvoicczfsynfa&dl=0

**Comment by quentin452** [comment]
ok i tried on my end and i have a better stacktrace , so i see whats the issue

**Comment by quentin452** [comment]
[optimizationsandtweaks-V1.2.6-1-7-10+865d12bd80-dirty.zip](https://github.com/quentin452/OptimizationsAndTweaks/files/13205915/optimizationsandtweaks-V1.2.6-1-7-10%2B865d12bd80-dirty.zip)

extract this dev build and use it

**Comment by quentin452** [comment]
Fixed?

**Comment by Omgise** [comment]
Yes, it has been repaired. Thank you for your help :)
