### ISSUE TITLE
[1.7.10]: OptimizationsAndTweaks causes a memory leak (loop?), with JustAnotherSpawner, as a result of which chunks cannot be loaded

### ISSUE THREAD

**Issue by kotmatross28729** [quentin452/Multithreadingandtweaks#56]
### Modpack

Custom / none

### Help isloating the issue

- [X] Did you tried to disabling some mixins in the mod config to see what mixin made the issue?
- [ ] Did you find what mixin made the issue?

### Game log

There's nothing in the logs that might be useful, no errors/warnings, none of that at all

### Description

According to my tests, the cause of this is [jas](https://github.com/makamys/JustAnotherSpawner)

(Possibly) If you test in a large modpack modpack - 1 initial chunk will load, the next chunks will not load, if you go to F3 and look at Used memory, you will see that the GC will clear memory very quickly, and there will be very quickly flash numbers

If you only run OptimizationsAndTweaks (+ dependencies) and JAS, then even the initial chunk will not load, you will simply spawn in void and will not be able to do anything.

in both cases, trying to exit to the main menu will lead to the "Shutting down internal server..." screen and this will last forever until you close the game yourself.

I tried turning off mixins that may have caused this, but it didn't help.
However, when I disabled all oat mixins , there was no problem, which means that this is happening because of some mixin, but I don’t know which one yet.

**Comment by quentin452** [comment]
caused by enableMixinPatchSpawnerAnimals
