### ISSUE TITLE
Server freeze

### ISSUE THREAD

**Issue by zeff9801** [quentin452/Multithreadingandtweaks#57]
### Help isloating the issue

- [ ] Did you tried to disabling some mixins in the mod config to see what mixin made the issue?
- [ ] Did you find what mixin made the issue?

### Game log

[stall-2023-11-05_16.43.13-1.txt](https://github.com/quentin452/OptimizationsAndTweaks/files/13260246/stall-2023-11-05_16.43.13-1.txt)

### Description

when trying to load the Hell dimension from JinGames Dragon Block C mod the server freezes, i tried disabling some chunk/world related mixins but that didn't fix the issue

**Comment by quentin452** [comment]
how to teleport to the Hell Dimension? i don't known anything about this mod

**Comment by zeff9801** [comment]
you should automatically get tped there when you die

**Comment by quentin452** [comment]
for my case , i don't get any logs about a crash but the server got freezed

**Comment by zeff9801** [comment]
yup my server doesn't crash i simply generated a stall report using https://www.curseforge.com/minecraft/mc-mods/sampler

**Comment by quentin452** [comment]
and i can confirm the tps is normal without Optimizationsandtweaks or all mixins disabled , so now just need to find what mixin :D

**Comment by quentin452** [comment]
and i found it , try disabling enableMixinPatchSpawnerAnimals

**Comment by zeff9801** [comment]
yup that did the trick thank you
