### ISSUE TITLE
[1.7.10]: Dragons can't be damaged

### ISSUE THREAD

**Issue by kuzuanpa** [quentin452/Multithreadingandtweaks#61]
### Modpack

no modpack

### Help isloating the issue

- [X] Did you tried to disabling some mixins in the mod config to see what mixin made the issue?
- [ ] Did you find what mixin made the issue?

### Game log

[latest.log](https://github.com/quentin452/OptimizationsAndTweaks/files/13367591/latest.log)

### Description

Dragons cannot be hurt whether using bow or sword or hand, Both EnderDragon and ChaosGuardian (From Draconic Evolution) affected. 

Mixins I tried disabling:
 MixinAxisAlignedBB MixinEntityArrowAttack MixinEntityLivingUpdate MixinEntityAINearestAttackableTarget MixinEntityLiving MixinEntityAgeable MixinEntityMoveHelper MixinEntityAIFollowParent MixinEntityAITasks

disabling them don't make any effects.

Mod installed:
UniMixin-0.1.7
falsePatternLib-0.12.5
OptimizationsAndTweaks-V1.4.2

**Comment by quentin452** [comment]
its caused by enableMixinChunk
