### ISSUE TITLE
[1.7.10]: OptimizationsAndTweaks breaks localization of optifine buttons + shaders don't work

### ISSUE THREAD

**Issue by kotmatross28729** [quentin452/Multithreadingandtweaks#66]
### Modpack

Custom

### Help isloating the issue

- [X] Did you tried to disabling some mixins in the mod config to see what mixin made the issue?
- [ ] Did you find what mixin made the issue?

### Game log

I don’t know how it can help, but here’s the log (incredibly a lot of spam): https://mclo.gs/qER8l0W

### Description

When launching oat with optifine, the names of the optifine buttons are broken (localization keys are visible, as if the lang file is broken, or is missing altogether?)

![Desktop Screenshot 2023 11 20 - 15 49 50 12](https://github.com/quentin452/OptimizationsAndTweaks/assets/110309314/7935c169-5917-4e1d-8417-d3a795088f08)

Also, when you try to enable shaders, they are selected, but in fact they do not work:
(shaders selected)
![Desktop Screenshot 2023 11 20 - 15 53 33 61](https://github.com/quentin452/OptimizationsAndTweaks/assets/110309314/d0765ab5-df4b-4085-aeb0-f0f98b7edc7b)

(but they don't work in the game)
![Desktop Screenshot 2023 11 20 - 15 53 40 08](https://github.com/quentin452/OptimizationsAndTweaks/assets/110309314/8097cb93-8c59-479c-b0ca-c7572a77d205)

When I turn off all mixins in the mod, then there is no error

**Comment by quentin452** [comment]
i don't have this problem , you should try updating oat?

**Comment by kotmatross28729** [comment]
Strange, but the problem is still present in V1.5.5, when testing, *do you have fastcraft enabled?* I just tried it, there is no problem with it, try with just optifine (I think this is again some kind of problem with inject)

**Comment by quentin452** [comment]
Ah ok infact the problem is that i have D6 (no problem) i tried E7 (and the problem appear)

**Comment by quentin452** [comment]
caused by enableMixinEntityRenderer
