### ISSUE TITLE
[1.7.10]: Crash with GTNH TCNEIAdditions 

### ISSUE THREAD

**Issue by xronin01** [quentin452/Multithreadingandtweaks#67]
### Help isloating the issue

- [ ] Did you tried to disabling some mixins in the mod config to see what mixin made the issue?
- [ ] Did you find what mixin made the issue?

### Game log

[latest.log](https://github.com/quentin452/OptimizationsAndTweaks/files/13417196/latest.log)

### Description

https://github.com/GTNewHorizons/TCNEIAdditions

**Comment by quentin452** [comment]
try this https://mega.nz/file/TwMhmIKR#atAC6r1pn_hB2hMBgCbmupslT4poLg14CanTTgC-xMc

**Comment by xronin01** [comment]
It worked

**Comment by xronin01** [comment]
Thank you
