### ISSUE TITLE
[1.7.10]: Server crash in the new version of the mod ( 0.7.4 )

### ISSUE THREAD

**Issue by MesTeiK-git** [quentin452/Multithreadingandtweaks#7]
### Game log

https://pastebin.com/VVHVRgmm

### Description

Mod Version: 0.7.4
Side: Server
Server Core: Crucible v5.4
Mods using mixins: Et Futurum Requiem, BugTorch, multithreadingtweaks.

**Comment by MesTeiK-git** [comment]
It looks like it's because of this mixin:
```
    # Enable multithreaded/batched TIleEntities rendering
    # [default: true]
    B:enableMixinTileEntities=false

```

**Comment by quentin452** [comment]
do you have a world , it will be easier to fix the issue

**Comment by quentin452** [comment]
ah you use crucible mc

**Comment by quentin452** [comment]
duplicated #6

**Comment by MesTeiK-git** [comment]
> duplicated #6

No. There's a completely different error. In your mod there is no check on the serverside and client side.

**Comment by quentin452** [comment]
let me try later to create a crucible mc server
