### ISSUE TITLE
[1.7.10]: Memory leak

### ISSUE THREAD

**Issue by zeff9801** [quentin452/Multithreadingandtweaks#73]
### Spark profiler

Performance

### Description

MixinModelRenderer causes huge memory leaks when enabled, as soon as i join my server the game starts filling all my computer ram, that doesn't happen in the vanilla lobby but only in the modded server

**Comment by quentin452** [comment]
Can you try : 
[unzip it.zip](https://github.com/quentin452/OptimizationsAndTweaks/files/13442958/unzip.it.zip)

edit : shouldn't be used , make crashes

**Comment by zeff9801** [comment]
![image](https://github.com/quentin452/OptimizationsAndTweaks/assets/48382312/18b8bf5f-57da-44be-93b2-315d93190378)

**Comment by quentin452** [comment]
its weird i don't have it even on large modpack

**Comment by zeff9801** [comment]
i will investigate it further once i have the time and let you know then

**Comment by quentin452** [comment]
maybe you should give to me your modpack
