### ISSUE TITLE
[1.7.10]: bug with rendering letters + crash with shift+f3 + player's hand is not rendered

### ISSUE THREAD

**Issue by kotmatross28729** [quentin452/Multithreadingandtweaks#76]
### Modpack

Custom / none

### Help isloating the issue

- [X] Did you tried to disabling some mixins in the mod config to see what mixin made the issue?
- [X] Did you find what mixin made the issue?

### Game log

Crash (shift+f3) - https://mclo.gs/oSPBQK9

### Mixins (what causes the error):

1) bug with rendering letters - MixinFontRenderer

2) crash with shift+f3 - MixinProfiler (mixin removed)

3) player's hand is not rendered - MixinModelRenderer

Also, in the case of optifine, if you test only with it, the player’s entire model will not be rendered at all, but if you use certain mods (I don’t know exactly which ones) then only your right hand will not be rendered

**Comment by quentin452** [comment]
Cannot reproduce any of these issues

**Comment by kotmatross28729** [comment]
strange, have you tried running only oat + deps / recreating the config? In a clean instance with oat V1.6.5, I can reproduce each of the errors

**Comment by quentin452** [comment]
yes , but do you have something that force unicode? because MixinFontRenderer have problems with Unicode

**Comment by kotmatross28729** [comment]
it seems not, but in V1.6.6 there seems to be no this problem (with text rendering), as well as a crash of the profiler (as far as I can see, because it was removed) But there is a problem with the invisible skin and optifine (I’ll say right away that I use E7 )

**Comment by quentin452** [comment]
MixinModelRenderer avoided from inject if optifine is present
