### ISSUE TITLE
[1.7.10]: PRIVATE @Overwrite method func_110997_a in mixins.optimizationsandtweaks.json:client.core.MixinTextureUtil from mod optimizationsandtweaks cannot reduce visibiliy of PUBLIC target method

### ISSUE THREAD

**Issue by kotmatross28729** [quentin452/Multithreadingandtweaks#80]
### Modpack

Custom / none

### Help isloating the issue

- [X] Did you tried to disabling some mixins in the mod config to see what mixin made the issue?
- [X] Did you find what mixin made the issue?

### Game log

https://mclo.gs/QxnsYvD

### Description

again an error with access method,  caused by  `B:enableMixinTextureUtil`

**Comment by quentin452** [comment]
already fixed in dev
