### ISSUE TITLE
[1.7.10]: All unicode fonts are dead. 

### ISSUE THREAD

**Issue by vasmark1** [quentin452/Multithreadingandtweaks#86]
### Modpack

My own

### Help isloating the issue

- [X] Did you tried to disabling some mixins in the mod config to see what mixin made the issue?
- [X] Did you find what mixin made the issue?

### Game log

-

### Description

enableMixinFontRenderer breaks unicode fonts, I have smoothfont installed if this matters something. With this option disabled it works great.

**Comment by vasmark1** [comment]
Also related to this issue: all text is supposed to be moved a bit left or it's a bug? Not critical, just reporting. 
![image](https://github.com/quentin452/OptimizationsAndTweaks/assets/65904048/628454c1-0091-4286-9303-acd3da3309d2)

**Comment by quentin452** [comment]
are you sure its caused by optimizationsandtweaks?

**Comment by vasmark1** [comment]
Yup, moved it away from mods folder and this happened: 
![image](https://github.com/quentin452/OptimizationsAndTweaks/assets/65904048/2c0d42f1-ee3a-4156-9154-e95b710d779d)

(it's a bit blurry cuz I've taken screenshot from inventory page)

**Comment by quentin452** [comment]
Can you make a new issue report for the F3 bug , for me in my modpack i don't have this bug, so there is an incompat with something

![Capture d’écran_2023-12-06_22-41-42](https://github.com/quentin452/OptimizationsAndTweaks/assets/42176772/d201b17e-233c-476b-80c8-2d814e80bf5c)

**Comment by vasmark1** [comment]
No problem, I'm so much happy that I've found alive 1.7.10 community and can help em like this
