### ISSUE TITLE
[1.7.10]: Something weird with tickrate happens

### ISSUE THREAD

**Issue by vasmark1** [quentin452/Multithreadingandtweaks#87]
### Modpack

My own, link provided

### Spark profiler

https://spark.lucko.me/VZSre7f783

### Description

My modpack: https://github.com/vasmark1/foxies

I don't know what exactly is causing this problem, but every 30-40 seconds tickrate goes up to 200-1000 ms and back to normal 6-10 for the rest time. I've created a new world so there is no structures or modded ores\entities. Also this happens only with o&t enabled.

**Comment by quentin452** [comment]
ok l'ill try the modpack

**Comment by quentin452** [comment]
![Capture d’écran_2023-12-06_22-29-28](https://github.com/quentin452/OptimizationsAndTweaks/assets/42176772/9c661e2b-e1d5-4fa0-bcee-be37d5f9abaa)

when i try your modpack,it seem its isn't updated or missing mods

**Comment by vasmark1** [comment]
Very strange, is witchery in mods folder? There supposed to be 145 elements in mods folder and all configs in config folder etc.

**Comment by quentin452** [comment]
for me there is 143 mods , and there is not witchery

**Comment by quentin452** [comment]
143 jar and 2 folders

**Comment by vasmark1** [comment]
So, I've removed witchery and WitcheryExtras, now loading into the game, mb it will not even crash. Even like this it supposed to work

**Comment by quentin452** [comment]
so for me i just need to remove WitcheryExtra?

**Comment by vasmark1** [comment]
witchery and witcheryextra, yes. If there was no witchery then it's google drive trouble - it not downloaded witchery to your pc. 
upd: just uploaded them into gd again to be sure

**Comment by quentin452** [comment]
So i tried making /forge tps alot of time for 40sec / 1 minutes and i don't have the bug , so its probably a JVM argument problem or maybe 33gb ram allocated is too much

**Comment by vasmark1** [comment]
Okay, I'll continue investigating this issue. Thank you for your work!

**Comment by vasmark1** [comment]
A bit more details: with O&T loaded used RAM goes up to 14-15%, and then resets to 9-10%, this is a place when a game microfreezes and thickrate goes up to 200+. I've checked JVM args, reseted them to defaults, also reduced RAM to 16gb. 

Maybe microfreeze happens because of conflict with some mod that cleans up RAM or idk? 

Update: Moved modpack from GD to GitHub, now all mods should be downloaded correctly. Somehow google found malware in witchery...

**Comment by Abalieno** [comment]
The 42 second thing may be due to the saving system.

It's something I see on every 1.7.10 and that is gone on 1.12, but it seems just due to Minecraft saving state to disk periodically every 42 or so seconds.

Also, never allocate more than 8Gb ram.
