### ISSUE TITLE
[1.7.10]: Gui problem

### ISSUE THREAD

**Issue by vasmark1** [quentin452/Multithreadingandtweaks#88]
### Modpack

My own, link provided

### Help isloating the issue

- [ ] Did you tried to disabling some mixins in the mod config to see what mixin made the issue?
- [ ] Did you find what mixin made the issue?

### Game log

[2023-12-07-2.log](https://github.com/quentin452/OptimizationsAndTweaks/files/13591945/2023-12-07-2.log)
hell lot of spam by foamfix or something, but here it is

### Description

all text is supposed to be moved a bit left or it's a bug?

Mod enabled: 
![image](https://github.com/quentin452/OptimizationsAndTweaks/assets/65904048/0e661d1d-859b-4cc4-8507-1ed30938087f)
Mod disabled: 
![image](https://github.com/quentin452/OptimizationsAndTweaks/assets/65904048/6194fdb6-a5cf-42cd-9d0a-97b510a2b42b)

**Comment by quentin452** [comment]
i can confirm the bug , the bug appear in your modpack and its appear even on buttons of menus

**Comment by vasmark1** [comment]
Yeah, I'll test more and try to find which mod is causing the problem

**Comment by quentin452** [comment]
So ok all mods marked has green are suspects , one of these mods cause the issue when OptimizationsAndTweaks is enabled
![Capture d’écran_2023-12-06_22-52-45](https://github.com/quentin452/OptimizationsAndTweaks/assets/42176772/db9d22c5-3138-4268-8fdc-9d78622b59a6)

**Comment by vasmark1** [comment]
Yup, I'll check em out

**Comment by quentin452** [comment]
the guilty is SmoothFont

**Comment by quentin452** [comment]
l'ill prevent MixinFontRenderer from being injected if SmoothFont is present to prevent the issue

**Comment by vasmark1** [comment]
Oh, thanks a lot!
SmoothFont is musthave in old versions, even tc4tweaks is not fixing unicode text in thaumonomicon being not-readable runes

**Comment by quentin452** [comment]
For me SmoothFont causing lags ,so i don't use it ,so i didn't got the issue

**Comment by vasmark1** [comment]
Yeah, if I play in English everything is good and SmoothFont is not needed, but unfortunately only I know English this good - all the rest people play on their own locales and unicode font causes a great problem

**Comment by quentin452** [comment]
ok
