### ISSUE TITLE
World corruption and crashes

### ISSUE THREAD

**Issue by Abalieno** [quentin452/Multithreadingandtweaks#91]
### Modpack

https://github.com/enmumne/Grumpy-GregTech-6

### Help isloating the issue

- [ ] Did you tried to disabling some mixins in the mod config to see what mixin made the issue?
- [ ] Did you find what mixin made the issue?

### Game log

not enough IDs crash:

[00:00:35] [Server thread/FATAL] [mixin/]: Mixin apply for mod neid failed mixins.neid.early.json:minecraft.MixinAnvilChunkLoader from mod neid -> net.minecraft.world.chunk.storage.AnvilChunkLoader: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/world/chunk/storage/AnvilChunkLoader::neid$overrideSetByteArray with priority 1000 cannot inject into net/minecraft/world/chunk/storage/AnvilChunkLoader::func_75820_a(Lnet/minecraft/world/chunk/Chunk;Lnet/minecraft/world/World;Lnet/minecraft/nbt/NBTTagCompound;)V merged by fr.iamacat.optimizationsandtweaks.mixins.common.core.MixinAnvilChunkLoader with priority 1000 [PREINJECT Applicator Phase -> mixins.neid.early.json:minecraft.MixinAnvilChunkLoader from mod neid -> Prepare Injections ->  -> redirect$bah000$neid$overrideSetByteArray(Lnet/minecraft/nbt/NBTTagCompound;Ljava/lang/String;[BLnet/minecraft/world/chunk/storage/ExtendedBlockStorage;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/world/chunk/storage/AnvilChunkLoader::neid$overrideSetByteArray with priority 1000 cannot inject into net/minecraft/world/chunk/storage/AnvilChunkLoader::func_75820_a(Lnet/minecraft/world/chunk/Chunk;Lnet/minecraft/world/World;Lnet/minecraft/nbt/NBTTagCompound;)V merged by fr.iamacat.optimizationsandtweaks.mixins.common.core.MixinAnvilChunkLoader with priority 1000 [PREINJECT Applicator Phase -> mixins.neid.early.json:minecraft.MixinAnvilChunkLoader from mod neid -> Prepare Injections ->  -> redirect$bah000$neid$overrideSetByteArray(Lnet/minecraft/nbt/NBTTagCompound;Ljava/lang/String;[BLnet/minecraft/world/chunk/storage/ExtendedBlockStorage;)V -> Prepare]

1.8.0 crash:

[main/FATAL] [mixin/]: Mixin apply for mod hodgepodge failed mixins.hodgepodge.early.json:minecraft.MixinWorldGetBlock from mod hodgepodge -> net.minecraft.world.World: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/world/World::hodgepodge$getBlock with priority 1000 cannot inject into net/minecraft/world/World::func_147439_a(III)Lnet/minecraft/block/Block; merged by fr.iamacat.optimizationsandtweaks.mixins.common.core.MixinWorld with priority 1000 [PREINJECT Applicator Phase -> mixins.hodgepodge.early.json:minecraft.MixinWorldGetBlock from mod hodgepodge -> Prepare Injections ->  -> redirect$zmh000$hodgepodge$getBlock(Lnet/minecraft/world/chunk/Chunk;III)Lnet/minecraft/block/Block; -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/world/World::hodgepodge$getBlock with priority 1000 cannot inject into net/minecraft/world/World::func_147439_a(III)Lnet/minecraft/block/Block; merged by fr.iamacat.optimizationsandtweaks.mixins.common.core.MixinWorld with priority 1000 [PREINJECT Applicator Phase -> mixins.hodgepodge.early.json:minecraft.MixinWorldGetBlock from mod hodgepodge -> Prepare Injections ->  -> redirect$zmh000$hodgepodge$getBlock(Lnet/minecraft/world/chunk/Chunk;III)Lnet/minecraft/block/Block; -> Prepare]

### Description

Crashes are due to some GTNH mods, I think.

Latest versions were crashing with latest notenoughIDs 1.5.3: https://github.com/GTNewHorizons/NotEnoughIds/releases
It was fine up to the menu screen, but it would load the world and then go back to title screen.

The current problem with 1.8.0 instead is some early crash due to mixin. I paste the relevant log above.

![ou io y](https://github.com/quentin452/OptimizationsAndTweaks/assets/4656436/c46e6cf6-9a46-4a28-a52b-1d854b711fdc)

![jl kl](https://github.com/quentin452/OptimizationsAndTweaks/assets/4656436/cc2bbaff-b0d8-48fa-abcd-34cae34524e8)

This other problem instead happens with optimizationsandtweaks-V1.7.2

I load into the world normally, but when I exit and enter again, chunks get deleted. I suppose it fails to save them properly on exit.

World corruption still happens on 1.6.9. Only 1.6.7 seems to be working properly.

**Comment by quentin452** [comment]
Can you try this?
[optimizationsandtweaks-V1.8.0-1-7-10.4+43df1c6ec8.zip](https://github.com/quentin452/OptimizationsAndTweaks/files/13679203/optimizationsandtweaks-V1.8.0-1-7-10.4%2B43df1c6ec8.zip)
unzip it

**Comment by Abalieno** [comment]
Won't run with the old notenoughIDs-1.7.10-1.4.6.jar
It sends me back to title screen without loading.

Now I'll try notenoughIDs-1.5.3.jar

**Comment by Abalieno** [comment]
Nope, both just send me back to title screen.

**Comment by quentin452** [comment]
Try making a new world

i got the issue , like can't join world if the bugged jar has been used before in the world

**Comment by Abalieno** [comment]
Didn't work on new world either (with notenoughIDs-1.5.3.jar)

**Comment by quentin452** [comment]
then try changing not enough ids to endlessids

**Comment by Abalieno** [comment]
Eh, nope. Gives even more issues. Falsepattern stuff is often incompatible with gtnh maintained mods.

**Comment by quentin452** [comment]
then idk , you say the 1.6.7 seem to be work correctly, in the dev version i gave, i removed the Mixin i added in V1.6.8 but issues continue to appear for you

**Comment by Abalieno** [comment]
If 1.6.7 works you'd have to remove changes AFTER that.

**Comment by quentin452** [comment]
anyway OptimizationsAndTweaks has configs , try finding the mixin that cause the issue

**Comment by quentin452** [comment]
I tried the modpack and for me all is ok with the mod

**Comment by Abalieno** [comment]
For me notenoughIDs-1.5.3.jar and optimizationsandtweaks-V1.6.7.jar work together. The world loads and there's no corruption.

After 1.6.7 I had to roll back notenoughIDs, or it would send me back to menu screen. But even if 1.6.9 loaded, it had world corruption on reload.

Always restoring from backup.

**Comment by quentin452** [comment]
idk , i removed the mixin thats i added in V1.6.8 (in the dev version) so l'ill watch commits

**Comment by Abalieno** [comment]
I haven't tested 1.6.8, only 1.6.9

**Comment by quentin452** [comment]
then you could try disabling one of these mixins , (MixinAnvilChunkLoader has been removed)
![Capture d’écran_2023-12-15_01-41-59](https://github.com/quentin452/OptimizationsAndTweaks/assets/42176772/41834e4a-d831-424a-a0b1-84e430e8d78e)

**Comment by quentin452** [comment]
or try the new dev build
[optimizationsandtweaks-V1.8.0-1-7-10.11+b448503d39.zip](https://github.com/quentin452/OptimizationsAndTweaks/files/13679631/optimizationsandtweaks-V1.8.0-1-7-10.11%2Bb448503d39.zip)
unzip it

**Comment by Abalieno** [comment]
[mixin/]: Mixin apply for mod neid failed mixins.neid.early.json:minecraft.MixinAnvilChunkLoader from mod neid -> net.minecraft.world.chunk.storage.AnvilChunkLoader: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/world/chunk/storage/AnvilChunkLoader::neid$overrideSetByteArray with priority 1000 cannot inject into net/minecraft/world/chunk/storage/AnvilChunkLoader::func_75820_a(Lnet/minecraft/world/chunk/Chunk;Lnet/minecraft/world/World;Lnet/minecraft/nbt/NBTTagCompound;)V merged by fr.iamacat.optimizationsandtweaks.mixins.common.core.MixinAnvilChunkLoader with priority 1000 [PREINJECT Applicator Phase -> mixins.neid.early.json:minecraft.MixinAnvilChunkLoader from mod neid -> Prepare Injections ->  -> redirect$bah000$neid$overrideSetByteArray(Lnet/minecraft/nbt/NBTTagCompound;Ljava/lang/String;[BLnet/minecraft/world/chunk/storage/ExtendedBlockStorage;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/world/chunk/storage/AnvilChunkLoader::neid$overrideSetByteArray with priority 1000 cannot inject into net/minecraft/world/chunk/storage/AnvilChunkLoader::func_75820_a(Lnet/minecraft/world/chunk/Chunk;Lnet/minecraft/world/World;Lnet/minecraft/nbt/NBTTagCompound;)V merged by fr.iamacat.optimizationsandtweaks.mixins.common.core.MixinAnvilChunkLoader with priority 1000 [PREINJECT Applicator Phase -> mixins.neid.early.json:minecraft.MixinAnvilChunkLoader from mod neid -> Prepare Injections ->  -> redirect$bah000$neid$overrideSetByteArray(Lnet/minecraft/nbt/NBTTagCompound;Ljava/lang/String;[BLnet/minecraft/world/chunk/storage/ExtendedBlockStorage;)V -> Prepare]

This is 1.6.8, it sends me to multiplayer screen, for some reason

**Comment by quentin452** [comment]
MixinAnvilChunkLoader has been removed (in later version)(DEV)

**Comment by Abalieno** [comment]
This last one seems to work.

optimizationsandtweaks-V1.8.0-1-7-10.11+b448503d39.jar

**Comment by quentin452** [comment]
you mean the new dev build?

edit : ok

**Comment by quentin452** [comment]
i can close this?
