### ISSUE TITLE
[1.7.10]: Thaumcraft Silverwood gen is broken

### ISSUE THREAD

**Issue by xronin01** [quentin452/Multithreadingandtweaks#92]
### Help isloating the issue

- [ ] Did you tried to disabling some mixins in the mod config to see what mixin made the issue?
- [ ] Did you find what mixin made the issue?

### Game log

[latest.log](https://github.com/quentin452/OptimizationsAndTweaks/files/13690165/latest.log)

### Description

![26f4f172-6593-42d6-afe9-2469fd7a66e4](https://github.com/quentin452/OptimizationsAndTweaks/assets/109928669/00a43fdc-db5e-4ca3-a210-dc5e794856dc)

**Comment by quentin452** [comment]
like the mixins isn't helpfull , i will delete it
