### ISSUE TITLE
2 things needs to improve

### ISSUE THREAD

**Issue by HowardZHY** [quentin452/Multithreadingandtweaks#93]
### Game log

/

### Description

1. The Copyright Header and mod info in https://github.com/quentin452/OptimizationsAndTweaks/blob/1.7.10/src/main/java/fr/iamacat/optimizationsandtweaks/Tags.java
is corrupt
2. Other mods classes not found caused large log spamming

**Comment by quentin452** [comment]
made in dev , but some errors can appear again , but the whole problem get fixed
