### ISSUE TITLE
[1.7.10]: MCHeli load speed suggestion

### ISSUE THREAD

**Issue by beeffeter456** [quentin452/Multithreadingandtweaks#95]
### Description

I know that coreTweaks exists for other mods, however the MCHeli mod specifically has really slow loading time for its models, even with coreTweaks installed. I am wondering if there is a possible implementation that would help speed the pre-initialzation stage up.

src: https://github.com/RagexPrince683/MCH-mocmaster

**Comment by quentin452** [comment]
Hum , MCHELI require a mod to work?
![image](https://github.com/quentin452/OptimizationsAndTweaks/assets/42176772/3e027948-772d-44a5-8cfd-4fe880de08c0)

**Comment by quentin452** [comment]
when i add MCHeli i can't launch the game so ...

**Comment by beeffeter456** [comment]
thats odd

the compiled version from modrinth should not give any issues:

https://modrinth.com/mod/mcheli-o/version/1.6

**Comment by quentin452** [comment]
what 500 MB :D thats probably why the mod taking long time to load

**Comment by quentin452** [comment]
i added the mod to mods folder and when i launch the game , the mod isn't loaded at all

**Comment by beeffeter456** [comment]
HBM's nuclear tech is also a required dependency: https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/releases/tag/1.0.27X4824

**Comment by quentin452** [comment]
added it and the mod can't load

**Comment by quentin452** [comment]
really idk

**Comment by quentin452** [comment]
![image](https://github.com/quentin452/OptimizationsAndTweaks/assets/42176772/22463052-aa67-48f4-835d-32544f8852d7)

**Comment by beeffeter456** [comment]
you need to unzip the MCHeli file

**Comment by GamebP** [comment]
why is that mod 500 mib?

**Comment by quentin452** [comment]
lol after unzipping the mod , now he load but the game is really slow to load now

**Comment by quentin452** [comment]
so the problem is registerModels : 
![image](https://github.com/quentin452/OptimizationsAndTweaks/assets/42176772/be916cf1-146b-4529-bd10-55e087def938)

**Comment by quentin452** [comment]
the problem is that there is no source(github) for Mcheli , modrinth don't have curse.maven alternative so cannot add the mod to dependencies indev

**Comment by quentin452** [comment]
but it seem that the Mcheli modelloader code from the original McHeli from Curseforge is pretty the same so i think i could try something

**Comment by quentin452** [comment]
problem when mixin classes from MCHELI , no mixin target found so wontfix
