### ISSUE TITLE
[1.7.10]: Can't startup with 2 other mods

### ISSUE THREAD

**Issue by xdeadstokex** [quentin452/Multithreadingandtweaks#97]
### Help isloating the issue

- [ ] Did you tried to disabling some mixins in the mod config to see what mixin made the issue?
- [ ] Did you find what mixin made the issue?

### Game log

[latest.log](https://github.com/quentin452/OptimizationsAndTweaks/files/13939094/latest.log)

### Description

can't start when all these 3 are used together (can start game with any 2 mods of the 3):
DragonAPI+1.7.10+V33b.jar
falsepatternlib-mc1.7.10-1.0.0.jar
optimizationsandtweaks-V1.11.6.jar

**Comment by GamebP** [comment]
dragonapi dosent like it so thats why

**Comment by xdeadstokex** [comment]
yep, i know dragonapi is a pain in the ass for a long time, many many bugs, but I have not try to disable any mixins config though, did disable all config and it works perfectly.

**Comment by quentin452** [comment]
its fixed lol in V1.11.7 :D

**Comment by xdeadstokex** [comment]
yep i see lol :D, I reply to the one above, so yeah, dragonapi is still a pain in the ass.
