### ISSUE TITLE
[1.7.10]: Crash with Alfheim

### ISSUE THREAD

**Issue by Rimusp** [quentin452/Multithreadingandtweaks#98]
### Help isloating the issue

- [ ] Did you tried to disabling some mixins in the mod config to see what mixin made the issue?
- [ ] Did you find what mixin made the issue?

### Game log

[fml-client-latest.log](https://github.com/quentin452/OptimizationsAndTweaks/files/13954547/fml-client-latest.log)

### Description

Crashes on load with Alfheim mod no idea where to even start with mixins

**Comment by quentin452** [comment]
fixed in dev now , to fix the crash just put to false 'enableMixinBiomeGenBase" in Optimizationsandtweaks

**Comment by Rimusp** [comment]
that worked but now it crashes when trying to create or load a world
[fml-client-latest.log](https://github.com/quentin452/OptimizationsAndTweaks/files/13954674/fml-client-latest.log)

**Comment by quentin452** [comment]
its probably a bug caused by Alfheim itself

**Comment by Rimusp** [comment]
ok will report to them thanks anyways

**Comment by Rimusp** [comment]
testet some mixins and found that "enableMixinEntityRenderer" is causing the crash
